---
title: "dyplr library vignette"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

# Purpose

This vignette aims to introduce you dyplr library. It is here for learning purposes.

# Reference

Dr. Bharatendra https://www.youtube.com/watch?v=rsfV57N7Uns&list=PL34t5iLfZddtUUABMikey6NtL05hPAp42&index=10

# Libraries

```{r setup, include=FALSE}

# Add DAAG to pull some data
library(DAAG)

# This is the library we will highlight here
library(dplyr)

knitr::opts_chunk$set(echo = TRUE)
```

# Datasets
```{r}
data()

# From the console, you can do:
# > ?datasetname
```

# DAAG

```{r}

# For example DAAG has 'possum'

data('possum')
str(possum)
summary(possum)
# Try from the console:
# > ?possum
```

# dyplr

## select

And example of a pipe function 

```{r}
# Select

# The shortcut for %>% is command + shift + m
possum %>% select(2:3, 4:7)
```

## filter()

```{r}

possum %>% filter(sex == 'f', Pop == 'Vic', age < 4)
```

## arrange()



```{r}

possum %>% filter(sex == 'f', Pop == 'Vic', age < 4) %>% arrange(desc(belly))

```

## summarise()



```{r}

possum %>% filter(sex == 'f', Pop == 'Vic', age < 4) %>% arrange(desc(belly)) %>% 
  summarise(Avg = mean(belly),
            SD = sd(belly),
            count = n())

```

## group_by()

It creates a table.

```{r}

possum %>% filter(sex == 'm') %>% 
  group_by(site) %>%
  summarise(Avg = mean(belly),
            SD = sd(belly),
            count = n())


```
## arrange() on that table created by group_by()

```{r}
# Add another function, descending order
possum %>% filter(sex == 'm') %>% 
  group_by(site) %>%
  summarise(Avg = mean(belly),
            SD = sd(belly),
            count = n()) %>%
  arrange(desc(Avg))



```

## Create a new table (mutate)

```{r}

# New variable TR
mytable <- possum %>% group_by(site) %>%
  summarise(TR = sum(taill) / sum(totlngth),
            count = n()) %>%
  arrange(desc(TR))

print(mytable)

```

