---
title: "Maps"
author: "Oscar A. Trevizo"
date: "`r Sys.Date()`"
output: 
  pdf_document: 
    toc: yes
    number_sections: yes
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Reference: Dr. Rai

# https://www.youtube.com/watch?v=SW5o8B_xtH8&list=PL34t5iLfZddug6PqUszo1u8d9ndME_ub9&index=2

# Load the libraries

```{r}
# Libraries
# library(leaflet)
library(tidyverse)
library(ggmap)
library(leaflet.extras)
library(htmltools)
library(ggplot2)
library(maps)
library(mapproj)
library(mapdata)

```


# World map


```{r}
w <- map_data('world')
icj <- map_data('world',
                region = c('Mexico', 'Canada', 'USA'))
ggplot(icj, aes(x = long, y = lat, group = group)) +
  geom_polygon(color = 'black') 

```

#


# Covid

## Prepare the data

```{r}
c <- read.csv('../data/covid.csv', header = TRUE)
usa <- c %>% filter(country == 'United States')
usa <- usa %>% group_by(province) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

```


## Merge the data

```{r}
# usa$province <- tolower(usa$province)
# c$province <- tolower(c$province)
# data <- merge(c, usa,
#               by.x = 'province',
#               by.y = 'province')
# 
# ggplot(data, aes(x = longitude, y = latitude, 
#                  group = province,
#                  fill = count)) +
#   geom_polygon(color = 'gray') 

```


