---
title: 'Intro to ISLR Lib'
output:
  html_document:
    toc: true
---

```{r setup, include=TRUE}
library(ISLR)
library(RColorBrewer)
library(reshape2)
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
```


# Vectorization

```{r vectperf}
##
#
# See how long it takes to do something
#
##

# Create some data

# Assign a matrix to variable x. Fill with normally distr random numbers
# Make it 10 columns by 50000 rows
x <- matrix(rnorm(50000*10), ncol=10)

# Make y numeric (coerse)
y <- numeric()

# Time stamp
pt1 <- proc.time()

# Iterate
for ( i in 1:dim(x)[1] ) y[i] <- mean(x[i,])

# Time stamp and then calculate how long it tok between pt1 and pt2
pt2 <- proc.time(); pt2-pt1; y[1:3]

# apply() is like Python lambda. Here, calculate the mean
y <- apply(x, 1, mean)

# Stamp time again, and measure the difference
pt3 <- proc.time(); pt3 - pt2; y[1:3]

y <- rowMeans(x)
proc.time() - pt3; y[1:3]
```

# ISLR Ch. 1

Datasets documentation https://www.rdocumentation.org/packages/ISLR/versions/1.4

## Fig.1.1

```{r wageplots,fig.width=9,fig.height=5}
##
#
# Run various plots for dataset Wage
#
##

# Wage is one of the datasets from ISLR library
class(Wage)
dim(Wage)
nrow(Wage)
ncol(Wage)
head(Wage)

# Set old.par to plot 1 row and 3 charts
old.par <- par(mfrow=c(1, 3), ps=16)

# Start with wage vs age
plot(Wage[,c("age", "wage")], xlab="Age", ylab="Wage", pch=20, col="gray")
# Add points
points(min(Wage$age):max(Wage$age),
       predict(loess(wage~age, Wage), newdata=data.frame(age=min(Wage$age):max(Wage$age))),
       col="blue",type="l",lwd=2)

# Now plot wage vs year
plot(Wage[,c("year","wage")],xlab="Year",ylab="Wage",pch=20,col="gray")
# Draw a regression line
abline(lm(wage~year,Wage),col="blue",lwd=2)

# Lastly a boxplot
boxplot(wage~substring(education,1,1),Wage,col=brewer.pal(5,"Dark2"),xlab="Education Level",ylab="Wage")  #YlGnBu RdYlGn Accent

par(old.par)
```

## Fig.1.2

```{r fig12plots,echo=FALSE,fig.width=9,fig.height=5}
##
#
# Run various plots for dataset Smarket
#
##

# Smarket is one of the datasets from ISLR library
class(Smarket)
dim(Smarket)
summary(Smarket)
head(Smarket)

old.par <- par(mfrow=c(1,3),ps=16)

for ( tmpLag in 1:3 ) {
  boxplot(as.formula(paste0("Lag", tmpLag, "~Direction")),
          Smarket,
          ylab="Percentage change in S&P",
          xlab="Today's Direction",
          main=c("Yesterday","Two Days Previous","Three Days Previous")[tmpLag],col=c("skyblue2","darkorange3"))
}
par(old.par)
```

Similar plots by `ggplot`:

```{r fig12ggplots,fig.width=9,fig.height=5}
##
#
# With ggplot()
#
##
ggplot(melt(Smarket[,c("Direction", paste0("Lag", 1:3))]), aes(x=Direction, y=value, fill=Direction)) +
  geom_boxplot() +
  facet_wrap(~variable) +
  theme(legend.position="none") +
  xlab("Today's Direction") +
  ylab("Percentage change in S&P")
```

